### ISSUE TITLE
click on user, will result all contacts deletion.

### ISSUE THREAD

**Issue by liubrian** [PSUCapstoneA/firefox-im#89]
If you have a contact list. Then click the drawer, click "User", then just hit "submit", without any change.

Your contact list will be gone!

**Comment by thechuck** [comment]
When editing a user we currently delete the existing user and create a new one with the new information.  This is what causes the contacts list to go away since it is part of the deleted user.  To fix this we need to either find a different way to change the user information or grab the contact information and place it in the newly created user.

**Comment by PSUCapstoneA** [comment]
I will fix it. Easy fix

**Comment by PSUCapstoneA** [comment]
This bug had been fixed tested by Chuck and Brian
